apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Socialize-Cluster
  region: us-east-1

vpc:
  id: vpc-0076250ea39e030c6
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0555bedf46a6f3535
      us-east-1c:
        id: subnet-050e2dcef1da90600
    # private:
    #   us-east-1a:
    #     id: subnet-083e6c24a30ae4ed2
    #   us-east-1b:
    #     id: subnet-083e6c24a30ae4ed2

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true