apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Socialize-Cluster
  region: us-east-1

vpc:
  id: vpc-0c87de90c47d1cc66
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0146f84220dcae4cb
      us-east-1b:
        id: subnet-00edbf8d7f8928bf2
    private:
      us-east-1a:
        id: subnet-08ae82b29a91fae83
      us-east-1b:
        id: subnet-070f478c372818421

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true