apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default-socialize
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socialize
  template:
    metadata:
      labels:
        app: socialize
    spec:
      containers:
        - name: socialize
          image: 095132937849.dkr.ecr.us-east-1.amazonaws.com/socialize:latest
          ports:
            - containerPort: 3000