apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: default-socialize
  labels:
    app: socialize
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: socialize